spring:
  application:
    name: uihell-backend
  flyway:
    enabled: true

  datasource:
    url: jdbc:postgresql://postgres:5432/uihell
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

server:
  port: 8080
